
services:
  - type: web
    name: ayumi-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: FREEDOMGPT_API_KEY
        sync: false
      - key: STABLE_HORDE_API_KEY
        sync: false
      - key: PORT
        value: 5000
